name: Sanitizers

on:
  # it's a bit slow so don't run on every pull request
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:  # Delete me - just to test it

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  sanitizers:
    strategy:
      fail-fast: false
      matrix:
        sanitizer: [address, undefined]  # memory
    uses: ./.github/workflows/compiled_python.yml
    with:
      compiler: clang
      sanitize: ${{ matrix.sanitizer }}
      name: ${{ matrix.sanitizer }}
